ALTER TABLE "appointment_types" ADD COLUMN "description" text;--> statement-breakpoint
CREATE INDEX "patient_allergies_patient_idx" ON "allergies" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "patient_alerts_patient_idx" ON "medical_alerts" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "patient_contacts_patient_idx" ON "patient_emergency_contacts" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "patients_org_status_idx" ON "patients" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "patients_org_phone_idx" ON "patients" USING btree ("organization_id","phone");--> statement-breakpoint
CREATE INDEX "patients_org_name_idx" ON "patients" USING btree ("organization_id","last_name","first_name");--> statement-breakpoint
CREATE INDEX "patients_org_patient_number_idx" ON "patients" USING btree ("organization_id","patient_number");--> statement-breakpoint
CREATE INDEX "clinical_notes_patient_created_idx" ON "clinical_notes" USING btree ("patient_id","created_at");--> statement-breakpoint
CREATE INDEX "clinical_notes_org_patient_idx" ON "clinical_notes" USING btree ("organization_id","patient_id");--> statement-breakpoint
CREATE INDEX "tooth_conds_patient_tooth_idx" ON "tooth_conditions" USING btree ("patient_id","tooth_code");--> statement-breakpoint
CREATE INDEX "tooth_conds_org_patient_idx" ON "tooth_conditions" USING btree ("organization_id","patient_id");--> statement-breakpoint
CREATE INDEX "appt_history_appt_idx" ON "appointment_status_history" USING btree ("appointment_id","changed_at");--> statement-breakpoint
CREATE INDEX "appts_org_time_idx" ON "appointments" USING btree ("organization_id","start_at","end_at");--> statement-breakpoint
CREATE INDEX "appts_dentist_time_idx" ON "appointments" USING btree ("dentist_id","start_at","end_at");--> statement-breakpoint
CREATE INDEX "appts_chair_time_idx" ON "appointments" USING btree ("chair_id","start_at","end_at");--> statement-breakpoint
CREATE INDEX "appts_patient_time_idx" ON "appointments" USING btree ("patient_id","start_at");--> statement-breakpoint
CREATE INDEX "appts_org_status_idx" ON "appointments" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "waiting_list_org_status_idx" ON "waiting_list_entries" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "procedures_patient_date_idx" ON "procedures" USING btree ("patient_id","performed_at");--> statement-breakpoint
CREATE INDEX "procedures_org_date_idx" ON "procedures" USING btree ("organization_id","performed_at");--> statement-breakpoint
CREATE INDEX "treat_defs_org_code_idx" ON "treatment_definitions" USING btree ("organization_id","code");--> statement-breakpoint
CREATE INDEX "treat_items_plan_status_idx" ON "treatment_plan_items" USING btree ("treatment_plan_id","status");--> statement-breakpoint
CREATE INDEX "treat_plans_patient_status_idx" ON "treatment_plans" USING btree ("patient_id","status");--> statement-breakpoint
CREATE INDEX "treat_plans_org_idx" ON "treatment_plans" USING btree ("organization_id","created_at");--> statement-breakpoint
CREATE INDEX "invoice_items_invoice_idx" ON "invoice_items" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "invoices_org_status_idx" ON "invoices" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "invoices_patient_created_idx" ON "invoices" USING btree ("patient_id","created_at");--> statement-breakpoint
CREATE INDEX "payments_invoice_idx" ON "payments" USING btree ("invoice_id");--> statement-breakpoint
CREATE INDEX "payments_org_date_idx" ON "payments" USING btree ("organization_id","paid_at");--> statement-breakpoint
CREATE INDEX "payments_patient_idx" ON "payments" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "recalls_org_status_due_idx" ON "recalls" USING btree ("organization_id","status","due_at");--> statement-breakpoint
CREATE INDEX "recalls_patient_idx" ON "recalls" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "revenue_attr_org_occurred_idx" ON "revenue_attributions" USING btree ("organization_id","occurred_at");--> statement-breakpoint
CREATE INDEX "revenue_opps_org_status_prio_idx" ON "revenue_opportunities" USING btree ("organization_id","status","priority");--> statement-breakpoint
CREATE INDEX "revenue_opps_patient_idx" ON "revenue_opportunities" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "voice_tasks_org_status_idx" ON "voice_call_tasks" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "voice_tasks_patient_idx" ON "voice_call_tasks" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "voice_tasks_opp_idx" ON "voice_call_tasks" USING btree ("opportunity_id");